name: Enable Feature
on:
  repository_dispatch:
    types:
      - active-task

jobs:
  test:
    name: Run Enable Feature
    runs-on: ubuntu-latest
    steps:
      - name: my active task
        run: |
          echo "Received active webhook, displaying received data"
          echo "type = ${{ github.event.client_payload.type }}"
          echo "shkeptncontext = ${{ github.event.client_payload.shkeptncontext }}"
          echo "id = ${{ github.event.client_payload.id }}"
      - name: send finished event
        run: |
          echo "Received active webhook, will send back Keptn finished event"
          json=$(cat <<-END
              {
                "data": {
                  "project":"${{ github.event.client_payload.project }}",
                  "stage": "${{ github.event.client_payload.stage}}",
                  "service": "${{ github.event.client_payload.service}}",
                  "status": "succeeded",
                  "result": "pass"
                },
                "source": "github",
                "specversion": "1.0",
                "type": "sh.keptn.event.mytask-active.finished",
                "shkeptncontext": "${{ github.event.client_payload.shkeptncontext }}",
                "triggeredid": "${{ github.event.client_payload.id }}"
              }
          END
          )
          echo "json=$json"
      - name: checkout
        uses: actions/checkout@v3

      # https://github.com/marketplace/actions/read-yaml
      - name: Run read-yaml action
        id: get-feature-flags
        uses: KJ002/read-yaml@main # You may wish to replace main with a version tag such as '1.6' etc.
        with:
          file: "./config.yml" # File to read from
          key-path: '["data", "config.json"]' # Access the runs key then the using key and returns the value.
      - name: check for variant
        uses: sergeysova/jq-action@v2
        id: variant-check
        with:
          cmd: echo '${{ steps.get-feature-flags.outputs.data }}' | jq '.flags."${{ github.event.client_payload.flag_key }}".variants.${{ github.event.client_payload.default_variant }}'
          multiline: true
      # Throw if null
      - name: echo default variant
        run: |
          echo "default variant found = ${{ steps.variant-check.outputs.value }}"

      - name: enable feature
        uses: sergeysova/jq-action@v2
        id: enable-feature
        with:
          cmd: |
            echo '${{ steps.get-feature-flags.outputs.data }}' |
            jq '.flags."${{ github.event.client_payload.flag_key }}".defaultVariant="${{ github.event.client_payload.default_variant }}"' |
            jq '.flags."${{ github.event.client_payload.flag_key }}".targeting={}'
          multiline: true
      - name: echo new config
        run: |
          echo "new config = ${{ steps.enable-feature.outputs.value }}"
      - name: Update values.yaml
        uses: fjogeleit/yaml-update-action@main
        with:
          valueFile: "config.yml"
          propertyPath: 'data["config.json"]'
          value: ${{ steps.enable-feature.outputs.value }}
          branch: enable-feature/${{ github.event.client_payload.flag_key }}
          targetBranch: master
          createPR: true
          message: "Update ${{ github.event.client_payload.flag_key }} default variant to '${{ github.event.client_payload.default_variant }}'"
          description: "Automated PR to do stuff!"
          labels: |
            shkeptncontext:${{ github.event.client_payload.shkeptncontext }},
            triggeredid:${{ github.event.client_payload.id }},
            project:${{ github.event.client_payload.project }},
            stage:${{ github.event.client_payload.stage}},
            service:${{ github.event.client_payload.service}}"
    # - name: update data
    #   run: |
    #     git checkout enable-feature
